# Generated by Django 4.1.2 on 2022-10-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100)),
                ('UserAddress', models.CharField(max_length=100)),
                ('UserPhone', models.CharField(max_length=50)),
            ],
        ),
    ]
